---
title: "SeinnaR"
author: "stt27@hi.is"
date: "now"
output: Rmarkdown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(kableExtra)
```

Hluti I

```{r}
#a
bss <- read_csv2("https://ahj.hi.is/kaupskra.csv", locale = locale(encoding = "ISO8859-1"))

#b
bss <- bss %>%
  filter(fullbuid == 1, 
         tegund %in% c("Fjolbyli", "Serbyli"),
         onothaefur_samningur == 1)

#c
bss <- bss %>%
  mutate(fermetraverd = kaupverd / einflm)

#d
bss <- bss %>%
  mutate(utgdag = as.Date(utgdag, format = "%Y-%m-%d"),
         ar = year(utgdag))

#e
bss_selected <- bss %>%
  filter(postnr %in% c(221, 200, 210))

serbyli_count <- bss_selected %>%
  filter(tegund == "Serbyli") %>%
  group_by(postnr) %>%
  summarise(fjoldi_serbyli = n())

serbyli_count %>%
  kbl(col.names = c("Póstnr.", "Fjöldi Sérbýla"), align = "c") %>%
  kable_classic_2(full_width = F)

#f-g
set.seed(37) # þið setjið happatöluna ykkar hér inn
bss_selected %>% 
group_by(postnr) %>%
sample_n(size = 200) -> urtak

```

Hluti II

```{r}
#h
fjolbyli_count <- urtak %>%
  filter(tegund == "Fjolbyli") %>%
  group_by(postnr) %>%
  summarise(fjoldi_fjolbyli = n())

serbyli_count <- urtak %>%
  filter(tegund == "Serbyli") %>%
  group_by(postnr) %>%
  summarise(fjoldi_serbyli = n())

byli_count <- right_join(fjolbyli_count, serbyli_count, by = "postnr")

byli_count %>%
  kbl(col.names = c("Póstnr.", "Fjöldi Sérbýla", "Fjöld fjölbýla"), align = "c") %>%
  kable_classic_2(full_width = F)

#i
percentage_table <- byli_count %>%
  group_by(postnr) %>%
  summarise(
    `Serbyli prósent` = sum(fjoldi_serbyli) / (sum(fjoldi_serbyli) + sum(fjoldi_fjolbyli)) * 100,
    `Fjolbyli prósent` = sum(fjoldi_fjolbyli) / (sum(fjoldi_serbyli) + sum(fjoldi_fjolbyli)) * 100
  )



```

Hluti III

```{r}

```

Hluti IV

```{r}

```
